language: python
cache:
  - pip
notifications:
  email: false
sudo: required
python:
  #~ - 2.7
  #~ - 3.5
  #~ - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
      - openssh-client
      - make
      - curl
      - wget
      - python3
      #~ - python3-distutils

install:
  #~ - sudo -E apt update
  #~ - sudo -E apt -yq --no-install-suggests --no-install-recommends install \-y make curl wget python3
  - pip install -e ./[tests]
  - pip install -e ./[docs]

script:
  - ./tests/test.sh
  - cd ./docs
  - make html
