language: python
cache:
  - pip
notifications:
  email: false
sudo: required
python:
  #~ - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
      - openssh-client
      - make
      - curl
      - wget
      - python3

install:
  - sudo -E ./tests/scripts/install_root.sh TRAVIS 3
  - ./tests/scripts/install.sh TRAVIS 3

script:
  - ./tests/scripts/test.sh TRAVIS
  - ./tests/scripts/docs.sh TRAVIS 3
